"""Add ScraperAccess model for platform credentials management

Revision ID: 258c96a8fa65
Revises: a60d69c6d657
Create Date: 2025-09-13 18:20:22.365490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '258c96a8fa65'
down_revision = 'a60d69c6d657'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scraper_access',
    sa.Column('platform_name', sa.String(length=100), nullable=False),
    sa.Column('platform_type', sa.String(length=50), nullable=False),
    sa.Column('platform_url', sa.String(length=255), nullable=True),
    sa.Column('access_data', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('last_verified', sa.DateTime(), nullable=True),
    sa.Column('last_scrape', sa.DateTime(), nullable=True),
    sa.Column('scrape_frequency', sa.String(length=20), nullable=False),
    sa.Column('auto_scrape', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('config_json', sa.JSON(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'platform_name', name='uq_company_platform')
    )
    with op.batch_alter_table('scraper_access', schema=None) as batch_op:
        batch_op.create_index('idx_scraper_company_active', ['company_id', 'is_active'], unique=False)
        batch_op.create_index('idx_scraper_platform_type_active', ['platform_type', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_scraper_access_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scraper_access_platform_name'), ['platform_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_scraper_access_platform_type'), ['platform_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scraper_access', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scraper_access_platform_type'))
        batch_op.drop_index(batch_op.f('ix_scraper_access_platform_name'))
        batch_op.drop_index(batch_op.f('ix_scraper_access_company_id'))
        batch_op.drop_index('idx_scraper_platform_type_active')
        batch_op.drop_index('idx_scraper_company_active')

    op.drop_table('scraper_access')
    # ### end Alembic commands ###
