"""Add booking model for reservation management

Revision ID: 2b8c83968d1b
Revises: fb63b8629241
Create Date: 2025-09-13 16:07:24.442959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b8c83968d1b'
down_revision = 'fb63b8629241'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('crm_reference_id', sa.String(length=100), nullable=True),
    sa.Column('booking_name', sa.String(length=255), nullable=False),
    sa.Column('arrival_date', sa.Date(), nullable=False),
    sa.Column('departure_date', sa.Date(), nullable=False),
    sa.Column('guest_count', sa.Integer(), nullable=False),
    sa.Column('guest_names', sa.Text(), nullable=True),
    sa.Column('schedine_sent_count', sa.Integer(), nullable=False),
    sa.Column('alloggiati_web_sent_date', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('booking_status', sa.String(length=50), nullable=False),
    sa.Column('property_unit_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['property_unit_id'], ['property_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bookings_arrival_date'), ['arrival_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_booking_name'), ['booking_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_booking_status'), ['booking_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_crm_reference_id'), ['crm_reference_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_departure_date'), ['departure_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_property_unit_id'), ['property_unit_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bookings_property_unit_id'))
        batch_op.drop_index(batch_op.f('ix_bookings_departure_date'))
        batch_op.drop_index(batch_op.f('ix_bookings_crm_reference_id'))
        batch_op.drop_index(batch_op.f('ix_bookings_booking_status'))
        batch_op.drop_index(batch_op.f('ix_bookings_booking_name'))
        batch_op.drop_index(batch_op.f('ix_bookings_arrival_date'))

    op.drop_table('bookings')
    # ### end Alembic commands ###
