"""Add invoice models - categories and invoices

Revision ID: 7f74b456634f
Revises: 075e3ca0b994
Create Date: 2025-09-13 14:56:08.172113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f74b456634f'
down_revision = '075e3ca0b994'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_categories_name'), ['name'], unique=True)

    op.create_table('subcategories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subcategories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subcategories_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_subcategories_name'), ['name'], unique=False)

    op.create_table('minicategories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subcategory_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['subcategory_id'], ['subcategories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('minicategories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_minicategories_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_minicategories_name'), ['name'], unique=False)

    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('supplier', sa.String(length=255), nullable=False),
    sa.Column('supplier_vat', sa.String(length=20), nullable=True),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=True),
    sa.Column('article_description', sa.Text(), nullable=True),
    sa.Column('article_code', sa.String(length=100), nullable=True),
    sa.Column('unit_of_measure', sa.String(length=20), nullable=True),
    sa.Column('period_start_date', sa.Date(), nullable=True),
    sa.Column('period_end_date', sa.Date(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('unit_price_with_vat', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('total_price_with_vat', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('unit_price_without_vat', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('total_price_without_vat', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('vat_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('vat_nature', sa.String(length=50), nullable=True),
    sa.Column('management_data_type', sa.String(length=100), nullable=True),
    sa.Column('management_text_ref', sa.String(length=255), nullable=True),
    sa.Column('payment_method', sa.String(length=100), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('subcategory_id', sa.Integer(), nullable=True),
    sa.Column('minicategory_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('allocation', sa.String(length=255), nullable=True),
    sa.Column('depreciation', sa.String(length=255), nullable=True),
    sa.Column('is_processed', sa.Boolean(), nullable=False),
    sa.Column('is_validated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['minicategory_id'], ['minicategories.id'], ),
    sa.ForeignKeyConstraint(['subcategory_id'], ['subcategories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoices_article_code'), ['article_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_invoice_date'), ['invoice_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_invoice_number'), ['invoice_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_supplier'), ['supplier'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_supplier_vat'), ['supplier_vat'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoices_supplier_vat'))
        batch_op.drop_index(batch_op.f('ix_invoices_supplier'))
        batch_op.drop_index(batch_op.f('ix_invoices_invoice_number'))
        batch_op.drop_index(batch_op.f('ix_invoices_invoice_date'))
        batch_op.drop_index(batch_op.f('ix_invoices_article_code'))

    op.drop_table('invoices')
    with op.batch_alter_table('minicategories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_minicategories_name'))
        batch_op.drop_index(batch_op.f('ix_minicategories_code'))

    op.drop_table('minicategories')
    with op.batch_alter_table('subcategories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subcategories_name'))
        batch_op.drop_index(batch_op.f('ix_subcategories_code'))

    op.drop_table('subcategories')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_name'))
        batch_op.drop_index(batch_op.f('ix_categories_code'))

    op.drop_table('categories')
    # ### end Alembic commands ###
