"""Add document status and temporary document management to invoices

Revision ID: c59869d365e1
Revises: 258c96a8fa65
Create Date: 2025-09-14 09:04:38.468703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c59869d365e1'
down_revision = '258c96a8fa65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('document_status', sa.String(length=20), nullable=False, server_default='invoice'))
        batch_op.add_column(sa.Column('is_final', sa.Boolean(), nullable=False, server_default='1'))
        batch_op.add_column(sa.Column('temp_reference', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('awaiting_invoice', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('linked_invoice_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_invoices_linked_invoice_id'), ['linked_invoice_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_temp_reference'), ['temp_reference'], unique=False)
        batch_op.create_foreign_key(None, 'invoices', ['linked_invoice_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_invoices_temp_reference'))
        batch_op.drop_index(batch_op.f('ix_invoices_linked_invoice_id'))
        batch_op.drop_column('linked_invoice_id')
        batch_op.drop_column('awaiting_invoice')
        batch_op.drop_column('temp_reference')
        batch_op.drop_column('is_final')
        batch_op.drop_column('document_status')

    # ### end Alembic commands ###
