"""Add property management models - PropertyType, POD, PropertyUnit, PropertyPod

Revision ID: fb63b8629241
Revises: 7f74b456634f
Create Date: 2025-09-13 15:49:30.328765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb63b8629241'
down_revision = '7f74b456634f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pods',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pod_code', sa.String(length=50), nullable=False),
    sa.Column('pod_type', sa.Enum('ELECTRICITY', 'GAS', 'WATER', 'HEATING', name='podtype'), nullable=False),
    sa.Column('supplier', sa.String(length=100), nullable=True),
    sa.Column('supplier_contract', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('power_capacity', sa.String(length=20), nullable=True),
    sa.Column('voltage', sa.String(length=20), nullable=True),
    sa.Column('meter_serial', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pods', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pods_pod_code'), ['pod_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_pods_pod_type'), ['pod_type'], unique=False)

    op.create_table('property_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('property_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_property_types_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_property_types_name'), ['name'], unique=True)

    op.create_table('property_units',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('square_meters', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('rooms', sa.Integer(), nullable=True),
    sa.Column('bathrooms', sa.Integer(), nullable=True),
    sa.Column('floor', sa.String(length=10), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=10), nullable=True),
    sa.Column('province', sa.String(length=5), nullable=True),
    sa.Column('property_type_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_occupied', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['property_type_id'], ['property_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('property_units', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_property_units_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_property_units_property_type_id'), ['property_type_id'], unique=False)

    op.create_table('property_pods',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('property_unit_id', sa.Integer(), nullable=False),
    sa.Column('pod_id', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pod_id'], ['pods.id'], ),
    sa.ForeignKeyConstraint(['property_unit_id'], ['property_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('property_pods', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_property_pods_pod_id'), ['pod_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_property_pods_property_unit_id'), ['property_unit_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_pods', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_property_pods_property_unit_id'))
        batch_op.drop_index(batch_op.f('ix_property_pods_pod_id'))

    op.drop_table('property_pods')
    with op.batch_alter_table('property_units', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_property_units_property_type_id'))
        batch_op.drop_index(batch_op.f('ix_property_units_name'))

    op.drop_table('property_units')
    with op.batch_alter_table('property_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_property_types_name'))
        batch_op.drop_index(batch_op.f('ix_property_types_code'))

    op.drop_table('property_types')
    with op.batch_alter_table('pods', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pods_pod_type'))
        batch_op.drop_index(batch_op.f('ix_pods_pod_code'))

    op.drop_table('pods')
    # ### end Alembic commands ###
