name: Simple Python Setup

on:
  workflow_dispatch:  # Allows manual trigger
  push:
    branches: [ main ]

jobs:
  setup:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Create and activate virtual environment
      run: |
        echo "Creating virtual environment..."
        python -m venv venv
        echo "Virtual environment created successfully!"
        
        echo "Activating virtual environment..."
        source venv/bin/activate
        echo "Virtual environment activated!"
        
        echo "Upgrading pip..."
        pip install --upgrade pip
        
        echo "Installing dependencies..."
        pip install -r requirements.txt
        
        echo "Setup completed successfully!"
    
    - name: Verify installation
      run: |
        source venv/bin/activate
        python --version
        pip list
